name: Auto deploy github actions

on:
  push:
    branches:
      - master

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      env:
        ACCESS_TOKEN: ${{ secrets.NAME_KNOWNLEDGE }}
    - run: npm install -g
    - run: npm run deploy:github