name: Auto deploy github actions

on:
  push:
    branches:
      - master

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: actions/checkout@master
      env:
        ACCESS_TOKEN: ${{ secrets.NAME_KNOWNLEDGE }}
        TARGET_REPO: zebing/knownledge
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: blog/.vuepress/dist/