name: Auto deploy github actions

on:
  push:
    branches:
      - master

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REPRO: zebing/knownledge

    - run: npm run deploy:github
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REPRO: zebing/knownledge